# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/'),
        ),
    ]
