# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0002_remove_home_slide_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=25)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_city', models.CharField(max_length=25)),
                ('contact_subject', models.CharField(max_length=75)),
                ('contact_message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
