# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0003_auto_20170821_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='slide_1_button_text',
            field=models.CharField(default='Book Noq', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slide_1_description',
            field=models.CharField(default='djhdfdlksfjalsjd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slide_1_title',
            field=models.CharField(default='kjfhdshfsdh', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slide_2_button_text',
            field=models.CharField(default='fsdf', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slide_2_description',
            field=models.CharField(default='dsdassd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slide_2_title',
            field=models.CharField(default='fdsfadsf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slide_3_button_text',
            field=models.CharField(default='dsfasdfdsaf', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slide_3_description',
            field=models.CharField(default='fdsafdasf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slide_3_title',
            field=models.CharField(default='fdsfads', max_length=50),
            preserve_default=False,
        ),
    ]
