# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0004_auto_20170821_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_description',
            field=models.CharField(max_length=150),
        ),
    ]
