# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0005_auto_20170821_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='slide_1_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='home',
            name='slide_2_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='home',
            name='slide_3_description',
            field=models.CharField(max_length=250),
        ),
    ]
