# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0006_auto_20170821_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='slide_1_button_text',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='home',
            name='slide_1_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='slide_2_button_text',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='home',
            name='slide_2_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='slide_3_button_text',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='home',
            name='slide_3_title',
            field=models.CharField(max_length=100),
        ),
    ]
