# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0010_auto_20170821_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_description',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=50),
        ),
    ]
