# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0011_auto_20170821_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='photography_album_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album1p', to='modeling.Album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='photography_album_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album2p', to='modeling.Album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='photography_album_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album3p', to='modeling.Album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='modeling_album_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album1m', to='modeling.Album'),
        ),
        migrations.AlterField(
            model_name='home',
            name='modeling_album_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album2m', to='modeling.Album'),
        ),
        migrations.AlterField(
            model_name='home',
            name='modeling_album_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album3m', to='modeling.Album'),
        ),
    ]
