# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0012_auto_20170821_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_photo', models.ImageField(default='media/None/no-img.jpg', upload_to='media/')),
                ('package_title', models.CharField(max_length=100)),
                ('package_quote_1', models.CharField(max_length=100)),
                ('package_quote_2', models.CharField(max_length=100)),
                ('package_cost', models.CharField(max_length=100)),
                ('package_description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='photography_package_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package1p', to='modeling.Album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='photography_package_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package2p', to='modeling.Album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='photography_package_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package3p', to='modeling.Album'),
            preserve_default=False,
        ),
    ]
