# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0015_auto_20170821_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_1_image', models.ImageField(default='media/None/no-img.jpg', upload_to='media/')),
                ('section_1_title', models.CharField(max_length=500)),
                ('section_1_subtitle', models.CharField(max_length=500)),
                ('section_1_bullet_1', models.CharField(max_length=500)),
                ('section_1_bullet_2', models.CharField(max_length=500)),
                ('section_1_bullet_3', models.CharField(max_length=500)),
                ('section_2_image', models.ImageField(default='media/None/no-img.jpg', upload_to='media/')),
                ('section_2_title', models.CharField(max_length=500)),
                ('section_2_subtitle', models.CharField(max_length=500)),
                ('section_2_description', models.CharField(max_length=500)),
                ('section_3_image', models.ImageField(default='media/None/no-img.jpg', upload_to='media/')),
                ('section_3_title', models.CharField(max_length=500)),
                ('section_3_subtitle', models.CharField(max_length=500)),
                ('section_3_description', models.CharField(max_length=500)),
                ('section_4_image', models.ImageField(default='media/None/no-img.jpg', upload_to='media/')),
                ('section_4_title', models.CharField(max_length=500)),
                ('section_4_subtitle', models.CharField(max_length=500)),
                ('section_4_description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
