# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0016_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_caption',
            field=models.CharField(max_length=100),
        ),
    ]
