# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0018_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='navbar',
            name='portfolio_1_action_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album1_1', to='modeling.Album'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='portfolio_1_action_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album1_2', to='modeling.Album'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='portfolio_2_action_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album2_1', to='modeling.Album'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='portfolio_2_action_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album2_2', to='modeling.Album'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='portfolio_3_action_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album3_1', to='modeling.Album'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='portfolio_3_action_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album3_2', to='modeling.Album'),
        ),
    ]
