# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0019_auto_20170823_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='collaborations_album_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album1c', to='modeling.Album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='collaborations_album_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album2c', to='modeling.Album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='collaborations_album_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album3c', to='modeling.Album'),
            preserve_default=False,
        ),
    ]
