# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0020_auto_20170824_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_caption',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_description',
        ),
    ]
