# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0021_auto_20170824_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_caption',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
