# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0022_auto_20170824_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255, verbose_name='Caption')),
                ('picture', models.ImageField(upload_to='media/', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='master_album',
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_cover',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_description',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_location',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='album',
            name='shoot_date',
        ),
        migrations.RemoveField(
            model_name='album',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='picture',
            name='master_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeling.Album', verbose_name='Album'),
        ),
    ]
