# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0023_auto_20170824_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='album_name',
        ),
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/'),
        ),
    ]
