# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0024_auto_20170824_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='caption',
            new_name='photo_caption',
        ),
        migrations.AddField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
