# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0025_auto_20170824_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_description',
            field=models.CharField(default='fdasfadsf', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='album_location',
            field=models.CharField(default='fdasfadsf', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='album_photographer',
            field=models.CharField(default='fdasfadsf', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='shoot_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/', verbose_name='Album Cover (240px x 240px)'),
        ),
    ]
