# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0027_auto_20170824_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=250)),
                ('promotion_percent', models.IntegerField()),
                ('promotion_start_date', models.DateTimeField()),
                ('promotion_end_date', models.DateTimeField()),
                ('promotion_terms', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='slide_1_button_link',
            field=models.CharField(default='/promotions', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slide_2_button_link',
            field=models.CharField(default='/promotions', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slide_3_button_link',
            field=models.CharField(default='/promotions', max_length=500),
            preserve_default=False,
        ),
    ]
