# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0028_auto_20170825_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'About Page'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Response', 'verbose_name_plural': 'Contact Responses'},
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page', 'verbose_name_plural': 'Contact Page'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Page'},
        ),
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': 'Navigation Bar', 'verbose_name_plural': 'Navigation Bar'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_link',
            field=models.CharField(default='/book', max_length=500),
            preserve_default=False,
        ),
    ]
