# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0029_auto_20170826_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red')], default='green', max_length=256),
            preserve_default=False,
        ),
    ]
