# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0030_album_album_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('Collaboration', 'collaboration'), ('Modeling', 'modeling'), ('Photography', 'photography')], max_length=256),
        ),
    ]
