# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0031_auto_20170826_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('collaboration', 'Collaboration'), ('modeling', 'Modeling'), ('photography', 'Photography')], max_length=256),
        ),
    ]
