# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20170825_1057'),
        ('modeling', '0032_auto_20170826_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_1', models.DateTimeField()),
                ('date_2', models.DateTimeField()),
                ('date_3', models.DateTimeField()),
                ('time_of_day', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=1000)),
                ('length_of_shoot', models.FloatField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.User')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='modeling.Package')),
            ],
            options={
                'verbose_name': 'Bookings',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
