# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0033_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_model',
            field=models.CharField(default='lucyraemallory', max_length=350, verbose_name='Model (Instagram Handle)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('collaboration', 'Collaboration'), ('modeling', 'Modeling'), ('photography', 'Photography'), ('senior photos', 'Senior Photos')], max_length=256),
        ),
    ]
